apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: notification-service-dev

# Base resources
resources:
- ../../manifests/deployment.yaml
- ../../manifests/service.yaml
- ../../manifests/hpa.yaml

# Dev-specific configurations
patchesStrategicMerge:
- deployment-patch.yaml

# Common labels for all resources
commonLabels:
  environment: dev
  managed-by: argocd

# Namespace for all resources
namespace: microservices-dev

# Images to use
images:
- name: acraksdemoprivatetwx8vb4d.azurecr.io/notification-service
  newTag: dev

# Resource name suffix for dev
nameSuffix: -dev
