apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: notification-service-production

# Base resources - use relative paths that work
resources:
- ../../manifests/deployment.yaml
- ../../manifests/service.yaml
- ../../manifests/loadbalancer.yaml
- ../../manifests/hpa.yaml
- ../../manifests/ingress.yaml

# Production-specific configurations
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: notification-service

# Common labels for all resources
labels:
- pairs:
    environment: production
    managed-by: argocd

# Namespace for all resources
namespace: microservices

# Images to use
images:
- name: acraksdemoprivatetwx8vb4d.azurecr.io/notification-service
  newTag: latest
