apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: notification-service-production
  annotations:
    config.kubernetes.io/local-config: "true"

# Base resources
resources:
- ../../manifests/deployment.yaml
- ../../manifests/service.yaml
- ../../manifests/loadbalancer.yaml
- ../../manifests/hpa.yaml
- ../../manifests/ingress.yaml

# Production-specific configurations
patchesStrategicMerge:
- deployment-patch.yaml

# Common labels for all resources
commonLabels:
  environment: production
  managed-by: argocd

# Namespace for all resources
namespace: microservices

# Images to use
images:
- name: acraksdemoprivatetwx8vb4d.azurecr.io/notification-service
  newTag: latest

# Resource name prefix
namePrefix: ""

# Resource name suffix  
nameSuffix: ""
