apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service-gitops
  namespace: argocd
  labels:
    app: notification-service
    tier: backend
    environment: production
spec:
  project: default
  
  # Source repository configuration - point directly to manifests
  source:
    repoURL: https://github.com/mmparmar553/notification-service-gitops.git
    targetRevision: main
    path: manifests
    
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
    
  # Sync policy configuration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
        
  # Health check configuration
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
